/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://iaidmtcctvcsfktfsjuexse4z4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hgppbb5cfvachcxr5546767try",
    "aws_cognito_identity_pool_id": "us-east-2:4d574408-d0e5-4bb2-bd57-0acc71710e7a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_TxNNEMqSX",
    "aws_user_pools_web_client_id": "5v9bk2gpi57d14s8tbmcf12pu3",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "ADDRESS",
        "BIRTHDATE",
        "EMAIL",
        "FAMILY_NAME",
        "NAME",
        "PHONE_NUMBER",
        "PREFERRED_USERNAME",
        "PICTURE",
        "PROFILE"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
